### ISSUE TITLE
Hardcoded path to UnityEditor Assemblies

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Malimbe#42]
The `FodyRunner.UntiyIntegration.csproj` has a hard coded path to the local UnityEditor/Engine files

`<UnityEditorAssembliesPath Condition="'$(UnityEditorAssembliesPath)' == ''">C:\Program Files\Unity\Hub\Editor\2018.3.7f1\Editor\Data\Managed\</UnityEditorAssembliesPath>`

Whilst this is probably the only way to include the path, there should be documentation explaining how it is updated, otherwise Malimbe will fail to compile unless the Unity assembly paths match (which they most likely won't)

**Comment by bddckr** [comment]
This is just a fallback path, as seen in the `Condition`.

MSBuild allows to specify such a property either when invoking, [which our CI uses](https://github.com/ExtendRealityLtd/DevOps/blob/450a6fd20d312d26ff0bdf3d991f0f35111262ed/templates/steps/ci.yml#L59), or (and in the case of a regular user building via Visual Studio) you can just create a file next to `FodyRunner.UntiyIntegration.csproj` called `FodyRunner.UntiyIntegration.csproj.user` with this as the content, to specify this property:
```xml
<PropertyGroup>
  <UnityEditorAssembliesPath>C:\My\Custom Unity\Installation Path\2018.3.7f1 or some other version\Editor\Data\Managed\</UnityEditorAssembliesPath>
</PropertyGroup>
```

**Comment by thestonefox** [comment]
```
<Project>
  <PropertyGroup>
    <UnityEditorAssembliesPath>path-to-your-unity-software-installation-editor-assemblies</UnityEditorAssembliesPath>
  </PropertyGroup>
</Project>
```

Will be part of documentation
