### ISSUE TITLE
unity 2019+ dll meta is modified

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Malimbe#48]
Create a new unity project,
git clone the vrtk into it
unity 2019+ will always modify the dll meta like the following

![image](https://user-images.githubusercontent.com/22952143/66699963-2e1d8880-ed1e-11e9-93d2-02cc90bcf8df.png)

**Comment by thestonefox** [comment]
Is this actually causing a problem?

**Comment by fight4dream** [comment]
This issue is fixed by using the upm. Thanks
