### ISSUE TITLE
[Help] to install 3rd party weavers

### ISSUE THREAD

**Issue by loic-lopez** [ExtendRealityLtd/Malimbe#55]
Hi everyone,

I would like to install this weaver : [https://github.com/Fody/MethodTimer](https://github.com/Fody/MethodTimer) but I don't know how because Unity does not support Nuget.

Thanks for reply.

**Comment by bddckr** [comment]
Some info can be found here:

https://docs.microsoft.com/en-us/visualstudio/cross-platform/unity-scripting-upgrade?view=vs-2019#add-packages-from-nuget-to-a-unity-project

https://github.com/xoofx/UnityNuGet

https://github.com/GlitchEnzo/NuGetForUnity

**Comment by loic-lopez** [comment]
@bddckr Thanks for reply, 
- xoofx/UnityNuGet use a curated list of nuget packages
- GlitchEnzo/NuGetForUnity does not install the right version of selected package

I will try out the microsoft documentation.

**Comment by loic-lopez** [comment]
@bddckr So moving `MethodTimer.Fody.dll` in `Assets/Plugins` result in : 
```
Unloading broken assembly Assets/Plugins/MethodTimer.Fody.dll, this assembly can cause crashes in the runtime
```

**Comment by bddckr** [comment]
Sounds like the .dll is not compiled against the .NET version your project is set to in Unity. This isn't related to Malimbe and thus the issues page on this project isn't the best place to get help with this sadly.
