### ISSUE TITLE
Malimbe.XmlDocumentationAttribute problem in Unity

### ISSUE THREAD

**Issue by castana1962** [ExtendRealityLtd/Malimbe#61]
Hi
I am making a Unity project with VTRK in Unity and I am having an error. This is the following
Malimbe.XmlDocumentationAttribute: The field 'VRTK.Prefabs.Interactions.InteractorVisibilityModifier.InteractorVisibilityModifierFacade/UnityEvent VRTK.Prefabs.Interactions.InteractorVisibilityModifier.InteractorVisibilityModifierFacade::Shown' is annotated to be documented by XML documentation comments but none were found.
For it, Could you help me with it?
Thanks for your time
Alejandro

**Comment by bddckr** [comment]
The mentioned property is documented as you can see here:
https://github.com/ExtendRealityLtd/VRTK.Prefabs/blob/bbc0e6d814b019ee2d48dd0834f4a6345fccce37/Interactions/InteractorVisibilityModifier/SharedResources/Scripts/InteractorVisibilityModifierFacade.cs#L26-L28

As such you should check the version of that package you have installed, and maybe attempt a reinstall.

Closing as this does neither belong into this repo (Malimbe is just a tool the mentioned `VRTK.Prefabs` project uses), nor is it reproducible as seen in the code snippet above.
